### ISSUE TITLE
出现def getUsers(self) -> list[User]: TypeError: 'type' object is not subscriptable这类错误

### ISSUE THREAD

**Issue by gocdn** [Levitans/-#11]
Traceback (most recent call last):
  File "D:/chaoxing/XueXiTongAutoFlush-master/main.py", line 17, in <module>
    from package.dataManger import UserDataManger, BrowserShow, BrowserConfiguration
  File "D:\chaoxing\XueXiTongAutoFlush-master\package\dataManger.py", line 14, in <module>
    class UserDataManger:
  File "D:\chaoxing\XueXiTongAutoFlush-master\package\dataManger.py", line 42, in UserDataManger
    def getUsers(self) -> list[User]:
TypeError: 'type' object is not subscriptable

Process finished with exit code 1
配置文件
[browser_config]
browser_is_display = 0
browser_path = C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe
browser_driver = D:\chaoxing\XueXiTongAutoFlush-master\chromedriver.exe

**Comment by Levitans** [comment]
我也不是很懂，为什么在你那边函数注释会报错，函数注释是python3之后才加入的，有没有可能是你python的版本比较低

**Comment by Levitans** [comment]
出现这个问题的原因找到了，是python版本太低。需要python3.9以上
