### ISSUE TITLE
登录成功，但不显示课程

### ISSUE THREAD

**Issue by 19819068211** [Levitans/-#6]
![屏幕截图(65)](https://user-images.githubusercontent.com/66981884/158774247-fb88634e-36dc-4c1e-8eb0-12eca16e09a9.png)
大佬，登录成功，但不显示课程

**Comment by Levitans** [comment]
目前发现不同的学校超星的页面元素是不一样的，程序可能是没找到你页面上的课程。
为了应对这种情况，现在程序的package/ControlWeb/learnable.py中有一个Learnable接口，你可以在package/ControlWeb/school.py中添加一个实现Learnable的类，相当于你的学校都可以用你实现的这个类，school.py中我实现了一个Fuist类，你可以参考这个来编写你的类


发件人: ***@***.***>
发送时间: 2022年3月17日 17:02
收件人: ***@***.***>
抄送: ***@***.***>
主题: [Levitans/XueXiTongAutoFlush] 登录成功，但不显示课程 (Issue #6)


[屏幕截图(65)]<https://user-images.githubusercontent.com/66981884/158774247-fb88634e-36dc-4c1e-8eb0-12eca16e09a9.png>
大佬，登录成功，但不显示课程

―

**Comment by Levitans** [comment]
目前发现不同的学校超星的页面元素是不一样的，程序可能是没找到你页面上的课程。
为了应对这种情况，现在程序的package/ControlWeb/learnable.py中有一个Learnable接口，你可以在package/ControlWeb/school.py中添加一个实现Learnable的类，相当于你的学校都可以用你实现的这个类，school.py中我实现了一个Fuist类，你可以参考我这个类来编写你的类

**Comment by 19819068211** [comment]
![屏幕截图(66)](https://user-images.githubusercontent.com/66981884/158932457-4eea244a-b7af-42b9-8420-fcc2f759cc7a.png)
请问答题搜索答案报错应该怎么办，

**Comment by 19819068211** [comment]
![屏幕截图(66)](https://user-images.githubusercontent.com/66981884/158932770-d953ada5-2baa-455d-922d-f21ba1b6395b.png)
请问搜索答题后报错应该怎么办

**Comment by Levitans** [comment]
你这个是之前的版本，现在答题的代码应该改过了，你用新的试一下

**Comment by 19819068211** [comment]
使用新版本答题时报错
  raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
![屏幕截图(67)](https://user-images.githubusercontent.com/66981884/158952869-2c047831-f083-4248-bed1-975e7efe6ce3.png)

**Comment by Levitans** [comment]
我刚添加了连接失败的判断，你拉取新的试试。查找答案用的是别人提供的接口，有的时候可能不稳定

**Comment by 19819068211** [comment]
好像都“体验新版”时，课程元素都是一样，可不可以实现登录自动使用新版呢
![屏幕截图(69)](https://user-images.githubusercontent.com/66981884/159104927-b5caa300-04e3-41ef-b455-5eae4ea8e3ed.png)
的

**Comment by Levitans** [comment]
有的账号进入学习通是新版，有的是旧版，我的账号进入的时候是新版所以当时没加上切换版本的。晚些会添加切换版本的功能，到时候你在试试

**Comment by Levitans** [comment]
有能力的话也可以向项目贡献代码哦，有些功能我可能因为时间关系就没加

**Comment by 19819068211** [comment]
![屏幕截图(70)](https://user-images.githubusercontent.com/66981884/159148819-b721bd29-6267-4d24-ac4b-2af211b7941c.png)
使用新版时，其他功能都是正常的，但答题时还是报错，请问有没有可能出一个修改题库接口的教程，谢谢
Traceback (most recent call last):
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
    self.do_handshake()
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jl\XueXiTongAutoFlush\main.py", line 156, in <module>
    xueXiTong.work()
  File "C:\Users\jl\XueXiTongAutoFlush\package\ControlWeb\xueXiTong.py", line 206, in work
    homework.getData()
  File "C:\Users\jl\XueXiTongAutoFlush\package\ControlWeb\task\answerQuestion\homework.py", line 44, in getData
    answerList = myGetAnswer.getAnswer(question, questionType)
  File "C:\Users\jl\XueXiTongAutoFlush\package\ControlWeb\task\answerQuestion\getAnswer.py", line 177, in getAnswer
    answerList = self.__requestAnswer(question, questionType)
  File "C:\Users\jl\XueXiTongAutoFlush\package\ControlWeb\task\answerQuestion\getAnswer.py", line 106, in __requestAnswer
    answer2 = future2.result(timeout=20)
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\jl\XueXiTongAutoFlush\package\ControlWeb\task\answerQuestion\getAnswer.py", line 37, in __API2
    r = requests.get(url, timeout=10)
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\jl\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by 19819068211** [comment]
比如这是题库接口返回数据，请问在get answer.py中应该如何修改呢
![Screenshot_20220320_135434_com guoshi httpcanary](https://user-images.githubusercontent.com/66981884/159150184-14281d50-0257-43fb-980e-fb35d72e2973.jpg)

**Comment by Levitans** [comment]
我给你说一下GetAnswer这个类的逻辑
第一步，把接口封装在一个函数中，我们向这函数中传入题目函数可以返回答案。在GetAnswer类中就是__API1(question)、__API2(question)、__API3(question)这三个函数
第二步，__requestAnswer(self, question, questionType)函数，这个函数会通过线程池同时调用第一步中的几个接口函数，将上面几个接口函数返回的答案存名为answerList的列表中。最后将answerList返回出来
第三步，getAnswer(self, question, questionType="")函数，这个函数是公共，getAnswer(self, question, questionType="")通过调用第二步的__requestAnswer(self, question, questionType)函数得到答案列表，去掉列表中的None并将列表返回。

上面就是GetAnswer类的逻辑，所以如果你要添加一个新的接口，就只用先分装一个接口的函数，然后在__requestAnswer()函数中加上你新添加的接口就行了。添加新接口记得要把15行的“self.__pool = ThreadPoolExecutor(max_workers=4)”中的4改一下，4表示线程池中有4个线程。

**Comment by Levitans** [comment]
你前面的那个异常，你可以单独运行getAnswer.py文件看看，我这边是没有出现过这个问题，我身边的人使用也没出现过

**Comment by 19819068211** [comment]
感谢作者大大，确实是我的问题，在电脑上运行get answer.py报错no module named package，在vps上运行程序就很完美，没有任何问题，感谢作者

**Comment by Levitans** [comment]
哈哈哈没什么，我会的也不多，也在边弄边学习
